import { Hono } from 'hono';
import type { UiResponse } from '@devvit/web/shared';
import { context, redis, reddit } from '@devvit/web/server';
import { getRecentLedgerUsers, getLedgerEntriesSince } from '../services/ledgerService';
import { ALERT_SENT_KEY } from '../utils/redisKeys';
import type { LedgerAction } from '../../shared/types';

const WINDOW_MS = 7 * 24 * 60 * 60 * 1000;
const OFFENSE_ACTIONS: Set<LedgerAction> = new Set(['remove', 'warn', 'tempban', 'permban']);

const ACTION_ICON: Record<LedgerAction, string> = {
  remove: '✂',
  warn: '⚠',
  tempban: '⏱',
  permban: '🚫',
  approve: '✓',
  note: '📝',
};

function fmtDate(ts: number): string {
  return new Date(ts).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
}

function pct(n: number, total: number): string {
  if (total === 0) return '0%';
  return `${Math.round((n / total) * 100)}%`;
}

export const modReportMenu = new Hono();

modReportMenu.post('/mod-report', async (c) => {
  const subredditName = context.subredditName;
  const since = Date.now() - WINDOW_MS;
  const now = Date.now();

  const userIds = await getRecentLedgerUsers(redis, since);

  const actionBreakdown: Record<LedgerAction, number> = {
    remove: 0, warn: 0, tempban: 0, permban: 0, approve: 0, note: 0,
  };
  const modBreakdown: Record<string, number> = {};
  const offenderCounts: Record<string, number> = {};
  let totalActions = 0;
  let playbookActions = 0;

  for (const userId of userIds) {
    const entries = await getLedgerEntriesSince(redis, userId, since);
    if (!entries.length) continue;

    for (const e of entries) {
      totalActions++;
      actionBreakdown[e.action] = (actionBreakdown[e.action] ?? 0) + 1;
      if (e.action !== 'note' && e.action !== 'approve') {
        offenderCounts[userId] = (offenderCounts[userId] ?? 0) + 1;
      }
      if (e.modId && e.modId !== 'PolicyPilot') {
        modBreakdown[e.modId] = (modBreakdown[e.modId] ?? 0) + 1;
      }
      if (e.usedPlaybook) playbookActions++;
    }
  }

  const topOffenders = Object.entries(offenderCounts)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 5);

  // Collect users with active threshold alerts
  const alertUsers: Array<{ userId: string; level: string }> = [];
  for (const userId of userIds) {
    const level = await redis.get(ALERT_SENT_KEY(userId));
    if (level) {
      const label = level === 'tempban' ? 'perm-ban threshold' : 'temp-ban threshold';
      alertUsers.push({ userId, level: label });
    }
  }

  // ─── Build markdown ───────────────────────────────────────────────────────

  const windowStart = fmtDate(since);
  const windowEnd = fmtDate(now);
  const title = `[PolicyPilot] Mod Report — ${new Date(now).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}`;

  const uniqueUsers = Object.keys(offenderCounts).length;
  const humanActions = totalActions - (actionBreakdown.note ?? 0);

  const summaryTable = [
    '| Metric | Value |',
    '|--------|-------|',
    `| Total actions logged | ${totalActions} |`,
    `| Human mod actions | ${humanActions} |`,
    `| Unique users actioned | ${uniqueUsers} |`,
    `| Playbook-assisted actions | ${playbookActions} (${pct(playbookActions, humanActions)}) |`,
    `| Active escalation alerts | ${alertUsers.length} |`,
  ].join('\n');

  const actionLines = (Object.entries(actionBreakdown) as [LedgerAction, number][])
    .filter(([, n]) => n > 0)
    .sort((a, b) => b[1] - a[1])
    .map(([action, n]) => `- ${ACTION_ICON[action]} **${action}**: ${n}`)
    .join('\n');

  const modLines = Object.entries(modBreakdown)
    .sort((a, b) => b[1] - a[1])
    .map(([mod, n]) => `- u/${mod}: ${n} action${n === 1 ? '' : 's'}`)
    .join('\n') || '- (none)';

  const offenderLines = topOffenders.length
    ? topOffenders.map(([userId, n], i) => `${i + 1}. u/${userId} — ${n} offense${n === 1 ? '' : 's'}`).join('\n')
    : '- No offenders in this period.';

  const alertLines = alertUsers.length
    ? alertUsers.map(({ userId, level }) => `- u/${userId} — ${level}`).join('\n')
    : '- No active escalation alerts.';

  const body = [
    `*7-day summary: ${windowStart} – ${windowEnd}*`,
    '',
    '---',
    '',
    '## Summary',
    summaryTable,
    '',
    '## Actions by Type',
    actionLines || '- No actions logged.',
    '',
    '## Actions by Moderator',
    modLines,
    '',
    '## Top 5 Offenders',
    offenderLines,
    '',
    '## Auto-Escalation Alerts',
    'Users currently at or above a configured threshold:',
    alertLines,
    '',
    '---',
    `*Generated by PolicyPilot · r/${subredditName}*`,
  ].join('\n');

  try {
    const post = await reddit.submitPost({
      subredditName,
      title,
      text: body,
    });

    return c.json<UiResponse>(
      {
        showToast: { text: 'Mod report posted!', appearance: 'success' },
        navigateTo: `https://reddit.com${post.permalink}`,
      },
      200
    );
  } catch (err) {
    console.error('PolicyPilot modReport: submitPost failed', err);
    return c.json<UiResponse>(
      { showToast: { text: 'Failed to create report post — check bot permissions.', appearance: 'neutral' } },
      200
    );
  }
});
